In [166]:
import pandas as pd
import numpy as np
import itertools as itr
import matplotlib.pyplot as plt
from ggplot import * ## requires ggplot: $ pip install ggplot, also note: https://github.com/yhat/ggplot/issues/417

In [167]:
path = r'C:\Users\darry\Documents\Projects\Udacity\Data Analyst Nanodegree\P2 Analyzing the NYC Subway Dataset\data\turnstile_weather_v2.csv'
df_raw = pd.read_csv(path)
df_raw

,UNIT,DATEn,TIMEn,ENTRIESn,EXITSn,ENTRIESn_hourly,EXITSn_hourly,datetime,hour,day_week,...,pressurei,rain,tempi,wspdi,meanprecipi,meanpressurei,meantempi,meanwspdi,weather_lat,weather_lon
0,R003,05-01-11,00:00:00,4388333,2911002,0,0,2011-05-01 00:00:00,0,6,...,30.22,0,55.9,3.5,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
1,R003,05-01-11,04:00:00,4388333,2911002,0,0,2011-05-01 04:00:00,4,6,...,30.25,0,52.0,3.5,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
2,R003,05-01-11,12:00:00,4388333,2911002,0,0,2011-05-01 12:00:00,12,6,...,30.28,0,62.1,6.9,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
3,R003,05-01-11,16:00:00,4388333,2911002,0,0,2011-05-01 16:00:00,16,6,...,30.26,0,57.9,15.0,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
4,R003,05-01-11,20:00:00,4388333,2911002,0,0,2011-05-01 20:00:00,20,6,...,30.28,0,52.0,10.4,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
5,R003,05-02-11,00:00:00,4388348,2911036,15,34,2011-05-02 00:00:00,0,0,...,30.31,0,50.0,6.9,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
6,R003,05-02-11,04:00:00,5818689,3874767,19,40,2011-05-02 04:00:00,4,0,...,30.27,0,50.0,4.6,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
7,R003,05-02-11,08:00:00,4388855,2911194,488,118,2011-05-02 08:00:00,8,0,...,30.30,0,53.1,10.4,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
8,R003,05-02-11,12:00:00,4389345,2911326,490,132,2011-05-02 12:00:00,12,0,...,30.24,0,57.0,11.5,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
9,R003,05-02-11,16:00:00,4389576,2911558,231,232,2011-05-02 16:00:00,16,0,...,30.16,0,59.0,11.5,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
10,R003,05-02-11,20:00:00,4389811,2911963,235,405,2011-05-02 20:00:00,20,0,...,30.15,0,55.9,4.6,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
11,R003,05-03-11,00:00:00,4389885,2912127,74,164,2011-05-03 00:00:00,0,1,...,30.13,0,54.0,4.6,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
12,R003,05-03-11,04:00:00,4389905,2912160,20,33,2011-05-03 04:00:00,4,1,...,30.11,0,51.8,5.8,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
13,R003,05-03-11,12:00:00,4390880,2912394,975,234,2011-05-03 12:00:00,12,1,...,30.07,0,60.8,9.2,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
14,R003,05-03-11,16:00:00,4391147,2912651,267,257,2011-05-03 16:00:00,16,1,...,29.98,0,66.0,9.2,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
15,R003,05-03-11,20:00:00,4391424,2913049,277,398,2011-05-03 20:00:00,20,1,...,29.95,0,62.1,11.5,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
16,R003,05-04-11,00:00:00,4391507,2913223,83,174,2011-05-04 00:00:00,0,2,...,29.94,1,59.0,9.2,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
17,R003,05-04-11,04:00:00,4391531,2913258,24,35,2011-05-04 04:00:00,4,2,...,29.91,1,60.1,0.0,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
18,R003,05-04-11,08:00:00,4392063,2913388,532,130,2011-05-04 08:00:00,8,2,...,29.94,1,55.4,15.0,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
19,R003,05-04-11,12:00:00,4392517,2913495,454,107,2011-05-04 12:00:00,12,2,...,29.96,1,51.1,11.5,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
20,R003,05-04-11,16:00:00,4392764,2913744,247,249,2011-05-04 16:00:00,16,2,...,29.96,1,48.0,18.4,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
21,R003,05-04-11,20:00:00,4392984,2914100,220,356,2011-05-04 20:00:00,20,2,...,30.01,1,50.0,16.1,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
22,R003,05-05-11,00:00:00,4393043,2914284,59,184,2011-05-05 00:00:00,0,3,...,30.01,0,48.9,16.1,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
23,R003,05-05-11,04:00:00,4393062,2914319,19,35,2011-05-05 04:00:00,4,3,...,29.98,0,48.0,12.7,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
24,R003,05-05-11,12:00:00,4394057,2914509,995,190,2011-05-05 12:00:00,12,3,...,29.91,0,60.8,15.0,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
25,R003,05-05-11,16:00:00,4394364,2914754,307,245,2011-05-05 16:00:00,16,3,...,29.88,0,63.0,19.6,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
26,R003,05-05-11,20:00:00,4394592,2915145,228,391,2011-05-05 20:00:00,20,3,...,29.94,0,57.9,12.7,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
27,R003,05-06-11,00:00:00,4394665,2915321,73,176,2011-05-06 00:00:00,0,4,...,29.97,0,55.0,3.5,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
28,R003,05-06-11,04:00:00,4394687,2915369,22,48,2011-05-06 04:00:00,4,4,...,29.96,0,52.0,8.1,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
29,R003,05-06-11,12:00:00,4395657,2915590,970,221,2011-05-06 12:00:00,12,4,...,29.94,0,68.0,16.1,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42619,R464,05-26-11,16:00:00,419894,95280,0,0,2011-05-26 16:00:00,16,3,...,29.89,0,69.1,9.2,0.000000,29.922000,66.640000,7.160000,40.660004,-73.844849
42620,R464,05-26-11,20:00:00,419894,95280,0,0,2011-05-26 20:00:00,20,3,...,29.88,0,66.9,8.1,0.000000,29.922000,66.640000,7.160000,40.660004,-73.844849
42621,R464,05-27-11,00:00:00,419894,95280,0,0,2011-05-27 00:00:00,0,4,...,29.92,0,66.0,4.6,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42622,R464,05-27-11,04:00:00,419894,95280,0,0,2011-05-27 04:00:00,4,4,...,29.94,0,64.0,3.5,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42623,R464,05-27-11,12:00:00,419894,95280,0,0,2011-05-27 12:00:00,12,4,...,29.99,0,73.0,12.7,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42624,R464,05-27-11,16:00:00,419894,95280,0,0,2011-05-27 16:00:00,16,4,...,29.93,0,75.9,20.7,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42625,R464,05-27-11,20:00:00,419894,95280,0,0,2011-05-27 20:00:00,20,4,...,29.96,0,66.9,21.9,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42626,R464,05-28-11,00:00:00,419894,95280,0,0,2011-05-28 00:00:00,0,5,...,30.00,0,66.0,4.6,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42627,R464,05-28-11,04:00:00,419894,95280,0,0,2011-05-28 04:00:00,4,5,...,30.00,0,64.0,6.9,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42628,R464,05-28-11,12:00:00,419894,95280,0,0,2011-05-28 12:00:00,12,5,...,30.05,0,77.0,11.5,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42629,R464,05-28-11,16:00:00,419894,95280,0,0,2011-05-28 16:00:00,16,5,...,30.05,0,73.9,15.0,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42630,R464,05-28-11,20:00:00,419894,95280,0,0,2011-05-28 20:00:00,20,5,...,30.06,0,68.0,13.8,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42631,R464,05-29-11,00:00:00,419894,95280,0,0,2011-05-29 00:00:00,0,6,...,30.09,0,66.0,9.2,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42632,R464,05-29-11,04:00:00,419894,95280,0,0,2011-05-29 04:00:00,4,6,...,30.09,0,64.9,6.9,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42633,R464,05-29-11,08:00:00,129127,35492,0,0,2011-05-29 08:00:00,8,6,...,30.13,0,66.2,6.9,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42634,R464,05-29-11,12:00:00,419894,95280,0,0,2011-05-29 12:00:00,12,6,...,30.13,0,75.9,10.4,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42635,R464,05-29-11,16:00:00,419894,95280,0,0,2011-05-29 16:00:00,16,6,...,30.06,0,75.0,18.4,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42636,R464,05-29-11,20:00:00,419894,95280,0,0,2011-05-29 20:00:00,20,6,...,30.08,0,70.0,15.0,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42637,R464,05-30-11,00:00:00,419894,95280,0,0,2011-05-30 00:00:00,0,0,...,30.09,1,64.9,5.8,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42638,R464,05-30-11,04:00:00,419894,95280,0,0,2011-05-30 04:00:00,4,0,...,30.04,1,66.9,3.5,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42639,R464,05-30-11,08:00:00,129127,35492,0,0,2011-05-30 08:00:00,8,0,...,30.09,1,72.0,13.8,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42640,R464,05-30-11,12:00:00,419894,95280,0,0,2011-05-30 12:00:00,12,0,...,30.10,1,82.9,8.1,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42641,R464,05-30-11,16:00:00,419894,95280,0,0,2011-05-30 16:00:00,16,0,...,30.06,1,82.0,9.2,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42642,R464,05-30-11,20:00:00,419894,95280,0,0,2011-05-30 20:00:00,20,0,...,30.10,1,73.0,4.6,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42643,R464,05-31-11,00:00:00,419894,95280,0,0,2011-05-31 00:00:00,0,1,...,30.13,0,72.0,0.0,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42644,R464,05-31-11,04:00:00,567311,132804,0,0,2011-05-31 04:00:00,4,1,...,30.14,0,73.0,6.9,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42645,R464,05-31-11,08:00:00,290767,59788,0,0,2011-05-31 08:00:00,8,1,...,30.19,0,80.1,6.9,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42646,R464,05-31-11,12:00:00,419894,95280,0,0,2011-05-31 12:00:00,12,1,...,30.20,0,81.0,10.4,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42647,R464,05-31-11,16:00:00,419894,95280,0,0,2011-05-31 16:00:00,16,1,...,30.17,0,77.0,13.8,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42648,R464,05-31-11,20:00:00,419894,95280,0,0,2011-05-31 20:00:00,20,1,...,30.18,0,69.1,4.6,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849

In [168]:
#df_rain = df_raw[df_raw.rain != 0]
#df_rain = df_raw.reset_index(drop = True)

In [169]:
#plot_rainent = ggplot(df_rain, aes(x = 'ENTRIESn_hourly')) +\
#    geom_histogram() +\
#    ggtitle('Total Hourly Entries (Obs with Rain)') +\
#    xlab('Entries Range') +\
#    ylab('Density')
#
#plot_rainent

In [170]:
#df_norain = df_raw[df_raw.rain == 0]
#df_norain = df_raw.reset_index(drop = True)

In [171]:
#plot_norainent = ggplot(df_norain, aes(x = 'ENTRIESn_hourly')) +\
#    geom_histogram() +\
#    ggtitle('Total Hourly Entries (Obs without Rain)') +\
#    xlab('Entries Range') +\
#    ylab('Density')
#
#plot_norainent

In [172]:
plot_entbyrain = ggplot(df_raw, aes('ENTRIESn_hourly', fill = 'rain')) +\
    geom_histogram(position = 'dodge') +\
    facet_wrap('rain') +\
    ggtitle("Total Hourly Entries (Obs with(top)/without(bottom) Rain)") +\
    xlab('Entries Range') +\
    ylab('Density')
    
plot_entbyrain

In [ ]:
# Data suggests a similar distribution for entry data on days where it rained vs. days where it did not rain. Note the greater
# amount of entry observations (distribution height) were recorded on days where it did not rain.

In [173]:
df_raw.station.unique()
df_sumbystat = df_raw.groupby('station', as_index = False).sum()
df_sumbystat = df_stat.sort('ENTRIESn_hourly')

In [174]:
df_sumbytopstat = df_sumbystat[-10:]
df_sumbytopstat

,station,ENTRIESn,EXITSn,ENTRIESn_hourly,EXITSn_hourly,hour,day_week,weekday,latitude,longitude,...,pressurei,rain,tempi,wspdi,meanprecipi,meanpressurei,meantempi,meanwspdi,weather_lat,weather_lon
184,ROOSEVELT AVE,14122303841,11054755492,1444569,1200120,1852,541,132,7538.131175,-13669.901785,...,5543.78,42,11575.6,1715.2,0.29,5543.78,11575.6,1715.2,7533.305450,-13669.315335
109,CHAMBERS ST,18541135465,15720716541,1452740,1258636,3720,1092,264,15145.718670,-27530.464872,...,11150.00,84,23582.6,2057.8,2.30,11150.00,23582.6,2057.8,15143.387532,-27533.531640
157,MAIN ST,24054590021,18264333309,1554806,1174953,1860,546,132,7581.281508,-13732.390416,...,5573.64,42,11635.7,1722.1,0.29,5573.64,11635.7,1722.1,7575.965814,-13734.230886
47,42 ST-GRD CNTRL,25565627027,13588473095,1555117,968557,1860,546,132,7579.843914,-13759.711770,...,5575.00,42,11791.3,1028.9,1.15,5575.00,11791.3,1028.9,7579.989552,-13760.135850
72,86 ST,30263728271,12550911889,1788577,708006,5528,1611,391,22441.797552,-40765.330650,...,16514.73,125,34959.0,3049.7,3.45,16514.73,34959.0,3049.7,22447.122366,-40756.210440
61,59 ST-COLUMBUS,26073384869,16950521617,1868674,1467338,1860,546,132,7582.868460,-13760.631726,...,5575.00,42,11791.3,1028.9,1.15,5575.00,11791.3,1028.9,7583.053344,-13762.101312
155,LEXINGTON AVE,30833183606,22787299781,1955971,1477588,5496,1613,389,22379.127097,-40608.009909,...,16455.48,124,34826.3,3040.4,3.37,16455.48,34826.3,3040.4,22375.175585,-40606.827866
49,42 ST-TIMES SQ,26834937069,19495797347,2360981,2043030,3712,1088,263,15120.440755,-27448.992984,...,11120.01,84,23524.7,2054.3,2.30,11120.01,23524.7,2054.3,15119.226472,-27446.292475
44,34 ST-PENN STA,52066169667,36329100254,2914046,2414830,5580,1638,396,22739.397078,-41287.909488,...,16725.00,126,35373.9,3086.7,3.45,16725.00,35373.9,3086.7,22734.881370,-41288.097720
43,34 ST-HERALD SQ,44562682980,29457052499,2920887,2001199,3720,1092,264,15158.826276,-27523.498428,...,11150.00,84,23582.6,2057.8,2.30,11150.00,23582.6,2057.8,15157.660428,-27521.154456

In [ ]:
#plot_sumentbydow = ggplot(df_sumbytopstat, aes(x = 'station', y = 'ENTRIESn')) \
#    + geom_bar(stat = 'identity') \
#    + ggtitle('Total Entries by Station') \
#    + xlab('Station') \
#    + ylab('Total Entries')
#plot_sumentbydow

In [ ]:
# The number of entries varies greatly depending on the station. Ridership is greatest for '34 ST-HERALD SQ' and
# '34 ST-PENN STA'.

In [175]:
df_sumbybotstat = df_sumbystat[:10]
df_sumbybotstat

,station,ENTRIESn,EXITSn,ENTRIESn_hourly,EXITSn_hourly,hour,day_week,weekday,latitude,longitude,...,pressurei,rain,tempi,wspdi,meanprecipi,meanpressurei,meantempi,meanwspdi,weather_lat,weather_lon
76,AQUEDUCT TRACK,69397414,15769920,0,0,1720,479,122,6872.929349,-12477.950394,...,5066.99,37,10490.9,1669.0,0.47,5066.99,10490.9,1669.0,6871.540676,-12479.779481
86,BEACH 36 ST,243830479,132260309,4712,20622,1752,502,126,7063.596294,-12835.665756,...,5215.56,40,10794.6,1747.3,0.47,5215.56,10794.6,1747.3,7073.337162,-12822.786624
172,ORCHARD BEACH,43770544,2378453,7559,309,896,238,65,3595.012696,-6496.871216,...,2632.83,32,5874.8,891.8,0.22,2632.83,5874.8,891.8,3594.301392,-6497.073088
88,BEACH 60 ST,930034257,1015362095,19342,54643,1648,471,117,6657.142776,-12101.312852,...,4916.07,34,10160.5,1658.5,0.46,4916.07,10160.5,1658.5,6668.240656,-12110.555236
87,BEACH 44 ST,256376055,357238875,29445,22502,1708,490,120,6819.659952,-12394.440744,...,5036.11,34,10412.3,1685.3,0.46,5036.11,10412.3,1685.3,6830.880672,-12405.934632
105,BUSHWICK AVE,332932302,337390640,36338,34257,1704,473,120,6712.622070,-12194.407665,...,4943.59,38,10337.3,1547.9,0.18,4943.59,10337.3,1547.9,6716.372520,-12193.954740
78,AVE H,522165241,644746769,36838,62772,1788,517,126,7231.991192,-13165.178684,...,5335.02,39,11304.3,990.7,1.11,5335.02,11304.3,990.7,7233.177028,-13165.021154
118,CYPRESS HILLS,713686911,474209742,37472,26364,1696,478,122,6835.910760,-12410.590752,...,5033.89,39,10507.4,1575.6,0.21,5033.89,10507.4,1575.6,6837.658464,-12413.045736
33,215 ST,940958607,305612290,45118,25759,1776,514,124,7152.137825,-12935.182575,...,5244.25,40,10978.5,1628.6,0.29,5244.25,10978.5,1628.6,7150.148250,-12934.605775
173,OXFORD-104 ST,610257601,541097136,45543,41108,1676,488,119,6793.851415,-12330.884377,...,5006.26,38,10384.3,1656.2,0.47,5006.26,10384.3,1656.2,6793.461971,-12333.134535

In [165]:
#plot_sumentbydow = ggplot(df_sumbybotstat, aes(x = 'station', y = 'ENTRIESn')) \
#    + geom_bar(stat = 'identity') \
#    + ggtitle('Total Entries by Station') \
#    + xlab('Station') \
#    + ylab('Total Entries')
#plot_sumentbydow

In [ ]:
# Ridership is lowest for 'OXFORD-104 ST' and '215 ST'.

In [176]:
df_sumentbydow = df_raw.groupby('day_week', as_index = False).sum()
df_meanentbydow = df_raw.groupby('day_week', as_index = False).mean()

In [177]:
plot_sumentbydow = ggplot(df_sumentbydow, aes(x = 'day_week', y = 'ENTRIESn_hourly')) \
    + geom_bar(stat = 'identity') \
    + ggtitle('Total Entries by Day of Week') \
    + xlab('Day of week (0 = Monday)') \
    + ylab('Total Entries')
plot_sumentbydow

In [178]:
plot_meanentbydow = ggplot(df_meanentbydow, aes(x = 'day_week', y = 'ENTRIESn_hourly')) \
    + geom_bar(stat = 'identity') \
    + ggtitle('Average Entries by Day of Week') \
    + xlab('Day of week (0 = Monday)') \
    + ylab('Average Entries')
plot_meanentbydow

In [65]:
df_sumentbyhr = df_raw.groupby('hour', as_index = False).sum()
df_meanentbyhr = df_raw.groupby('hour', as_index = False).mean()

In [68]:
plot_sumentbyhr = ggplot(df_sumentbyhr, aes(x = 'hour', y = 'ENTRIESn_hourly')) \
    + geom_bar(stat = 'identity') \
    + ggtitle('Total Entries by Hour of Day') \
    + xlab('Hour of Day (0 = 12:00am)') \
    + ylab('Total Entries')
plot_sumentbyhr

In [ ]:
# Total/average entry data over a single week shows that weekdays have greater ridership than weekends.

In [180]:
plot_meanentbyhr = ggplot(df_meanentbyhr, aes(x = 'hour', y = 'ENTRIESn_hourly')) \
    + geom_bar(stat = 'identity') \
    + ggtitle('Average Entries by Hour of Day') \
    + xlab('Hour of Day (0 = 12:00am)') \
    + ylab('Total Entries')
plot_meanentbyhr

In [ ]:
# Average entry data over a single day shows a greater ridership from midday onwards.